# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: twistcli-rasp@1
  inputs:
    twistlockService: 'prisma'
    appID: 'mydocker'
    consoleHost: 'https://us-west1.cloud.twistlock.com/us-3-159240883'
    dataFolder: '/twistlock'
    dockerfile: '**/Dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'myDockerhub'
    repository: 'abdullah8554/devops-project'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
- task: prisma-cloud-compute-scan@1
  inputs:
    scanType: 'images'
    twistlockService: 'prisma'
    artifact: 'abdullah8554/devops-project'
