apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}
  replicas: {{.Values.replicas}} # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: devops
        image: {{.Values.image}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{.Values.port}}
